package view.panels;

public class ClientsPanel extends javax.swing.JPanel {

    
    int numberOfClientInLine;
    
    public ClientsPanel() {
        initComponents();
        numberOfClientInLine = 0;
    }
    
    public void updateNumberOfClients(){
        String numberTxt = String.valueOf(numberOfClientInLine);
        this.clientNumber.setText(numberTxt);
    }
    
    public void incrementNumber(){
        numberOfClientInLine++;
        updateNumberOfClients();
    }
    
    public void decrementNumber(){
        numberOfClientInLine--;
        updateNumberOfClients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JLabel();
        clientNumber = new javax.swing.JLabel();

        panelTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        panelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTitle.setText("Clients in line");

        clientNumber.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        clientNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientNumber.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addComponent(clientNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientNumber;
    private javax.swing.JLabel panelTitle;
    // End of variables declaration//GEN-END:variables
}
